# Generated by Django 3.1.3 on 2020-11-15 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='subscribed',
            new_name='is_subscribed',
        ),
    ]
